---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oraxe
spec:
  serviceName: oraxe
  replicas: 1
  selector:
    matchLabels:
      app: oraxe
  template:
    metadata:
      labels:
        app: oraxe
    spec:
      containers:
      - name: oraxe
        image: container-registry.oracle.com/database/express:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: ORACLE_PWD
          value: "password"
        ports:
        - name: port1521
          containerPort: 1521
        - name: port5500
          containerPort: 5500
        volumeMounts:
        - name: oradata
          mountPath: /opt/oracle/oradata
  volumeClaimTemplates:
  - metadata:
      name: oradata
    spec:
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: 20Gi

---
apiVersion: v1
kind: Service
metadata:
  name: oraxe-service
spec:
  selector:
    app: oraxe
  type: NodePort
  ports:
  - name: port1521
    protocol: TCP
    port: 1521
    targetPort: 1521
  - name: port5500
    protocol: TCP
    port: 5500
    targetPort: 5500